# Generated by Django 2.2.12 on 2021-02-01 02:05

from django.db import migrations, models
import django.db.models.deletion

from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from pengajuan.models import Pengajuan , Terima

new_group, created = Group.objects.get_or_create(name='Super Admin')
new_group, created = Group.objects.get_or_create(name='Sekum Divisi IT')
new_group, created = Group.objects.get_or_create(name='GH Sekum Divisi IT')
new_group, created = Group.objects.get_or_create(name='Project Management')
new_group, created = Group.objects.get_or_create(name='GH Project Management')
new_group, created = Group.objects.get_or_create(name='Business Intelligence & Analythic')
new_group, created = Group.objects.get_or_create(name='GH Business Intelligence & Analythic')
new_group, created = Group.objects.get_or_create(name='Application Management Core & Non Core')
new_group, created = Group.objects.get_or_create(name='GH Application Management Core & Non Core')
new_group, created = Group.objects.get_or_create(name='Network, Security & Risk Management')
new_group, created = Group.objects.get_or_create(name='GH Network, Security & Risk Management')
new_group, created = Group.objects.get_or_create(name='Operation Management DC & DRC')
new_group, created = Group.objects.get_or_create(name='GH Operation Management DC & DRC')
new_group, created = Group.objects.get_or_create(name='Helpdesk & Support')
new_group, created = Group.objects.get_or_create(name='GH Helpdesk & Support')
new_group, created = Group.objects.get_or_create(name='Planning and Governance')
new_group, created = Group.objects.get_or_create(name='GH Planning and Governance')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengajuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=50, null=True)),
                ('nama_barang', models.CharField(max_length=50)),
                ('group_id', models.CharField(max_length=150)),
                ('spesifikasi', models.TextField(max_length=350)),
                ('jumlah', models.IntegerField(blank=True, default=0, null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('receive_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('landasan_kebutuhan', models.TextField(max_length=350)),
                ('gambar', models.ImageField(null=True, upload_to='gambar/')),
                ('nomor_memo', models.CharField(max_length=20)),
                ('tanggal_memo', models.DateField(null=True)),
                ('perihal_memo', models.CharField(max_length=250)),
                ('harga_barang', models.PositiveIntegerField(null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('jumlah2', models.IntegerField(default=0, null=True)),
                ('tl', models.IntegerField(default=0, null=True)),
                ('htl', models.IntegerField(default=0, null=True)),
                ('jumlah3', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemilik', models.CharField(max_length=60)),
                ('divisi', models.CharField(max_length=80)),
                ('merk', models.CharField(max_length=150)),
                ('jabatan', models.CharField(max_length=150)),
                ('nomor_barang', models.CharField(max_length=90, null=True)),
                ('tanggal_terima', models.DateField(null=True)),
                ('tipe', models.CharField(max_length=150)),
                ('nama_penyerah', models.CharField(max_length=90)),
                ('pemimpin_user', models.CharField(max_length=80)),
                ('pemimpin_pgo', models.CharField(max_length=85)),
                ('pengajuans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengajuan.Pengajuan')),
            ],
        ),
    ]
